### PR TITLE
Better implementation of attaching comments

### PR DESCRIPTION
**Pull request by kirill-konshin**
In new implementation comments are applied to AST immediately after it was created, this makes traversing of AST safer.
Tests are feeling good plus I have placed extra assertions.

### CODE REVIEW

**Comment by joeuy** [comment]
Could we support this option also on shimed modules?

**Comment by kirill-konshin** [comment]
What is wrong with shims? As far as I remember they were working...

**Comment by joeuy** [comment]
Using the following configuration, license comments got stripped from shim modules

"amdConfig": {
	"preserveComments": true,
	"shim": {
		"jQuery": {
			"exports": "jQuery",
			"preserveComments": true
		}
		...
	}

**Comment by kirill-konshin** [comment]
Can you 

Best regards
Kirill Konshin

**Comment by kirill-konshin** [comment]
Disregard previous message, can you create a separate ticket and I'll look into your issue.

**Pull request merged**
